version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
    depends_on:
      - postgres_fletmax
      - redis_fletmax
    user: "www-data"

  postgres_fletmax:
    image: postgres:15
    container_name: postgres_fletmax
    restart: unless-stopped
    environment:
      POSTGRES_DB: fletmax
      POSTGRES_USER: fletmax
      POSTGRES_PASSWORD: fletmax1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin_fletmax:
    image: dpage/pgadmin4
    container_name: pgadmin_fletmax
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: fletmax1234
    ports:
      - "8085:80"
    depends_on:
      - postgres_fletmax

  nginx_fletmax:
    image: nginx:latest
    container_name: nginx_fletmax
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  redis_fletmax:
    image: redis:latest
    container_name: redis_fletmax
    restart: unless-stopped
    ports:
      - "6381:6379"

volumes:
  postgres_data: