services:
  - type: web
    name: fleetmaax
    env: docker
    plan: free
    buildCommand: docker build -t fleetmaax .
    startCommand: /usr/local/bin/start-render.sh
    envVars:
      - key: APP_NAME
        value: FleetMaax
      - key: APP_KEY
        value: base64:JBL32gZF4EDlxgJDENEXK75GsrLZCnaLSWVy3v9ZQfk=
      - key: APP_URL
        value: https://fleetmaax.onrender.com
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: VITE_APP_URL
        value: https://fleetmaax.onrender.com
      - key: ASSET_URL
        value: https://fleetmaax.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: fleetmaax-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: fleetmaax-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: fleetmaax-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: fleetmaax-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: fleetmaax-db
          property: password
      - key: PORT
        value: 80 